frase = '  Curso em vídeo Python  '
print(f' Toda a frase: {frase}')
print(f' Frase na posição 1:3, contando os espaços - {frase[1:3]}')
print(f' Frase na posição inicial até a 15 [:15] com espaços, o posição 15 não mostra: {frase[:15]}')
print(f' Frase na posição 0 até indefinido [0:_] :{frase[0:]}')
print(f' Frase na posição 0 0::2 até indefinido pulado de 2 em 2: {frase[0::2]}')
print(f'Quantas vezes aparece a letra (o): {frase.count("o")}')
print(f'Quantas vez aparece a letra (O) convertendo em miúsculo: {frase.upper().count("O")}')
print('Tamanho de frase com espaços é: {}'.format(len(frase)))
print('Tamanho de frase sem espaços é: {}'.format(len(frase.strip())))
print('Trocando a frase:', frase.replace('Python', 'Android'))
print('\033[31m Localizando a palavra vídeo \033[m dentro da string: ', frase.find('vídeo'))
print('Modificando pra Maiúscula e \033[32m Localizando vídeo dentro da string: \033[m', frase.upper().find('VDEO'))
print('Dividindo a frase em listas: ', frase.split())
dividido = frase.split()
print('Mostrando uma variavel com uma lista de frase: {}'.format(dividido[0]))
print('Mostrando uma variavel com uma lista de frase na posicao 3: {}'.format(dividido[2][3]))
print("""Lorem Ipsum is simply dummy text of the printing and typesetting industry.\n
  """)
